print(" Name :  WARISHA KHAN")
print("Contact : 03352705523")
print ("Email : warikhan1397@gmail.com")
print("Address : C-15 Rufi Heights phase-1 block-17 Gulistan-e-jauhar Karachi")
print("_______________________________________________________________________________________________________________\n")
print("OBJECTIVE: Seeking a position in a good oraganization where my potentials will be fully discovered while working for the company dedicatedly.\n")
print("EDUCATION ")
print("------------------")
print("BACHELORS IN SOFTWARE ENGINEERING 2017-2020 ")
print("Sir syed university of engineering and technology")
print("INTERMEDIATE 2016")
print("Govt. girls degree college block 13 Gulistan-e-Jauhar")
print("MATRICULATION")
print("Al Behria School\n")
print("SKILLS")
print("------------------")
print(">MS OFFICE   >C LANGUAGE   >JAVA   >HTML & CSS   >PYTHON   >NETWORKING   >MSQL DATABASE\n")
print("ACHEIVEMENTS")
print("------------------------")
print(">JAVA certified from aptech")
print(">selection in PIAIC(Artificial Intelligence)")
print(">Received Star Student award & certificate in school")
print(">Received Well Behaved certificate in school\n")
print("STRENGTHS")
print("----------------")
print(">Communication   >Web designing   >Coding   >Team work   >Focused   >Passionate   >Time Management\n")
print("EXPERIENCE")
print("----------------")
print("5 weeks experience in MUTEX SYSTEMS.LTD")

